class Test
{
	public main() => ()
	{
		int x = getResult();
	}	
	
	public getResult() => (int)
	{
		try
		{
			throw Exception:create();
		
		}
		catch(Exception e)
		{
			return 4;
		}
		finally
		{
			return 7;
		}	
		
		return 9;
	}
}