import shadow.standard@Error;
import shadow.io@Console;

immutable class shadow.test@ExceptionTest
{
	public test() => () {
		throw ExceptionA:create();
	}
	public test1() => () {
		try {
			test();
		} catch (ExceptionA ex) {
			Console:instance.printLine("test1 caught ExceptionA");
		}
	}
	public test2() => () {
		try {
			test1();
		} catch (ExceptionA ex) {
			Console:instance.printLine("test2 caught ExceptionA");
		} catch (ExceptionB ex) {
			Console:instance.printLine("test2 caught ExceptionB");
		}
	}
	public test3() => () {
		try {
			test2();
		} catch (Exception ex) {
			Console:instance.printLine("test3 caught Exception");
		}
	}
	public main( String[] args ) => ( int ) {
		test3();
		return 0;
	}
}
